jobs:
  - name: api-intensive-remove
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Deployment
        labelSelector: { kube-burner-job: api-intensive }
        apiVersion: apps/v1

  - name: ensure-pods-removal
    qps: 10
    burst: 10
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Pod
        labelSelector: { kube-burner-job: api-intensive }

  - name: remove-services
    qps: 2
    burst: 2
    jobType: delete
    waitForDeletion: true
    objects:
      - kind: Service
        labelSelector: { kube-burner-job: api-intensive }

  - name: remove-configmaps-secrets
    qps: 2
    burst: 2
    jobType: delete
    objects:
      - kind: ConfigMap
        labelSelector: { kube-burner-job: api-intensive }
      - kind: Secret
        labelSelector: { kube-burner-job: api-intensive }
