---
jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: false
    cleanup: false
    waitWhenFinished: false
    objects:
      - name: du-workload-remove
        qps: 2
        burst: 2
        jobType: delete
        waitForDeletion: true
        objects:
          - kind: Deployment
            labelSelector: {kube-burner-job: du-workload}
            apiVersion: apps/v1

      - name: ensure-pods-removal
        qps: 10
        burst: 10
        jobType: delete
        waitForDeletion: true
        objects:
          - kind: Pod
            labelSelector: {kube-burner-job: du-workload}

      - name: remove-services
        qps: 2
        burst: 2
        jobType: delete
        waitForDeletion: true
        objects:
          - kind: Service
            labelSelector: {kube-burner-job: du-workload}

      - name: remove-configmaps-secrets
        qps: 2
        burst: 2
        jobType: delete
        objects:
          - kind: ConfigMap
            labelSelector: {kube-burner-job: du-workload}
          - kind: Secret
            labelSelector: {kube-burner-job: du-workload}
      - name: remove-volumes
        qps: 2
        burst: 2
        jobType: delete
        objects:
          - kind: PersistentVolume
            labelSelector: {kube-burner-job: du-workload}
