---
jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: true
    cleanup: true
    waitWhenFinished: true
    maxWaitTimeout: 5m
    errorOnVerify: true
    objects:

    # Template of Gu Pods with fedora-stress-ng
      - objectTemplate: templates/deployment.yaml
        replicas: 1
        inputVars:
          Image: {{ .FEDORA_STRESSNG_TEST_IMAGE }}
      - objectTemplate: templates/service.yaml
        replicas: 1
      - objectTemplate: templates/configmap1.yaml
        replicas: 1
      - objectTemplate: templates/configmap2.yaml
        replicas: 1
      - objectTemplate: templates/secret1.yaml
        replicas: 1
      - objectTemplate: templates/secret2.yaml
        replicas: 1
      - objectTemplate: templates/secret3.yaml
        replicas: 1
      - objectTemplate: templates/secret4.yaml
        replicas: 1

    # Template of Burstable pod with pvc 
      # - objectTemplate: templates/deployment-burstable.yaml
      #   replicas: 1
      #   inputVars:
      #     Image: {{ .FEDORA_STRESSNG_TEST_IMAGE }}
      # - objectTemplate: templates/deployment-pv.yaml
      #   replicas: 1
      # - objectTemplate: templates/deployment-pvc.yaml
      #   replicas: 1

    # Template of burstable pods with exec probes
      - objectTemplate: templates/webserver-deployment.yaml
        replicas: 10
        inputVars:
          Image: {{ .NGINX_TEST_IMAGE }}
      - objectTemplate: templates/webserver-service.yaml
        replicas: 10
      - objectTemplate: templates/curl-deployment.yaml
        replicas: 10
        inputVars:
          Image: {{ .CURL_TEST_IMAGE }}

    # Templates of burstable pods with kubeapiserver reqs
      - objectTemplate: templates/kubectlapp-serviceaccount.yaml
        replicas: 10
      - objectTemplate: templates/kubectlapp-role.yaml
        replicas: 10
      - objectTemplate: templates/kubectlapp-rolebinding.yaml
        replicas: 10
      - objectTemplate: templates/kubectlapp-deployment.yaml
        replicas: 10
        inputVars:
          Image: {{ .KUBECTL_TEST_IMAGE }}
