---
metricsEndpoints:
  - metrics:
      - metrics.yml
    indexer:
      type: local
      metricsDirectory: collected-metrics

# global:
#   measurements:
#     - name: podLatency

jobs:
  - name: du-emulator
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: false
    cleanup: false
    waitWhenFinished: false
    objects:
      - objectTemplate: templates/deployment.yaml
        replicas: 15
      - objectTemplate: templates/configmap.yaml
        replicas: 1
      - objectTemplate: templates/secret.yaml
        replicas: 1
      - objectTemplate: templates/service.yaml
        replicas: 1

  # - name: api-intensive-patch
  #   jobType: patch
  #   jobIterations: 1
  #   qps: 2
  #   burst: 2
  #   objects:
  #     - kind: Deployment
  #       objectTemplate: templates/deployment_patch_add_label.json
  #       labelSelector: { kube-burner-job: api-intensive }
  #       patchType: "application/json-patch+json"
  #       apiVersion: apps/v1
  #     - kind: Deployment
  #       objectTemplate: templates/deployment_patch_add_pod_2.yaml
  #       labelSelector: { kube-burner-job: api-intensive }
  #       patchType: "application/apply-patch+yaml"
  #       apiVersion: apps/v1
  #     - kind: Deployment
  #       objectTemplate: templates/deployment_patch_add_label.yaml
  #       labelSelector: { kube-burner-job: api-intensive }
  #       patchType: "application/strategic-merge-patch+json"
  #       apiVersion: apps/v1
