---
# metricsEndpoints:
#   - metrics:
#       - metrics.yml
#     indexer:
#       type: local
#       metricsDirectory: collected-metrics

# global:
#   measurements:
#     - name: podLatency

jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: false
    cleanup: false
    waitWhenFinished: false
    objects:
      - objectTemplate: templates/deployment.yaml
        replicas: 15
        inputVars:
          registry: {{ .REGISTRY }}
      - objectTemplate: templates/configmap.yaml
        replicas: 15
      - objectTemplate: templates/secret.yaml
        replicas: 15
      - objectTemplate: templates/service.yaml
        replicas: 15
