---
# metricsEndpoints:
#   - metrics:
#       - metrics.yml
#     indexer:
#       type: local
#       metricsDirectory: collected-metrics

# global:
#   measurements:
#     - name: podLatency

jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: workload
    podWait: false
    cleanup: false
    waitWhenFinished: false
    objects:
    # Template of Gu Pods with fedora-stress-ng
      - objectTemplate: templates/deployment.yaml
        replicas: 15
        inputVars:
          registry: {{ .REGISTRY }}
      
      - objectTemplate: templates/service.yaml
        replicas: 15
      
      
      - objectTemplate: templates/configmap1.yaml
        replicas: 15
      - objectTemplate: templates/configmap2.yaml
        replicas: 15

      - objectTemplate: templates/secret1.yaml
        replicas: 15
      - objectTemplate: templates/secret2.yaml
        replicas: 15
      - objectTemplate: templates/secret3.yaml
        replicas: 15
      - objectTemplate: templates/secret4.yaml
        replicas: 15

    # Template of burstable pods with exec probes
      - objectTemplate: templates/webserver-deployment.yml
        replicas: 1

      - objectTemplate: templates/webserver-service.yml
        replicas: 1

      - objectTemplate: templates/curl-deployment.yml
        replicas: 1
