apiVersion: v1
kind: Secret
metadata:
  {{ if eq .group nil }}
  name: secret-{{ or .Replica 0 }}
  {{ else }}
  name: secret-{{ .group }}-{{ or .Replica 0 }}
  {{ end }}
type: Opaque
{{ if eq .data nil }}
data: {{ .data | toJson }}
{{ else }}
data:
  password: Zm9vb29vb29vb29vb29vbwo=
{{ end }}