    apiVersion: v1
    kind: Service
    metadata:
      name: service-{{ or .Replica 0 }}
    spec:
      selector:
        service-label: du-workload-gu-{{ or .Replica 0 }}
      ports:
          - port: {{ or .port 80 }}
            targetPort: {{ or .targetPort 80 }}
  