kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubectlapp-{{ or .Replica 0 }}
  # namespace: workload
spec:
  template:
    metadata:
      labels:
        name: kubectlapp-{{ or .Replica 0 }}
    spec:
      serviceAccountName: kubectlapp-sa-{{ or .Replica 0 }}
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: kubectlapp
          image: "{{ .Image }}"
          command: ["/bin/sh","-c"]
          args:
          - |
            while true; do
              kubectl get pods -n workload
              kubectl get services -n workload
              sleep 1
            done
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: kubectlapp-{{ or .Replica 0 }}
  strategy:
    type: RollingUpdate