kind: Service
apiVersion: v1
metadata:
  name: webserver-{{ or .Replica 0 }}
spec:
  selector:
    name: webserver-{{ or .Replica 0 }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
