kind: Deployment
apiVersion: apps/v1
metadata:
  name: kubectlapp-{{.Replica}}-{{.Iteration}}
  namespace: workload
spec:
  template:
    metadata:
      labels:
        name: kubectlapp-{{.Replica}}-{{.Iteration}}
    spec:
      serviceAccountName: kubectlapp-sa-{{.Replica}}-{{.Iteration}}
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: kubectlapp
          image: bitnami/kubectl:latest
          command: ["/bin/sh"]
          args: ["-c", "while true; do kubectl get pods -n workload; sleep 5; done"]
      restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      name: kubectlapp-{{.Replica}}-{{.Iteration}}
  strategy:
    type: RollingUpdate